server:
  port: 8081

---
spring:
  config:
    activate:
      on-profile: dev
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:postgresql://localhost:5432/JavaMicro
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 12345678Ll
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true
    default-schema: diplom_netology_db
    contexts: dev
  jpa:
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: diplom_netology_db
    hibernate:
      ddl-auto: validate
  sql:
    init:
      mode: always
      continue-on-error: true
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    ru.netology: DEBUG
    org.springframework.web: INFO
  file:
    name: ./logs/cloudstore-dev-app.log
cors:
  settings:
    mapping: "/**"
    credentials: true
    origins: "http://localhost:8080"
    headers: "*"
    methods:
      - GET
      - POST
      - PUT
      - DELETE
project:
  filesystem:
    type: "windows"
---
spring:
  config:
    activate:
      on-profile: prod
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    url: jdbc:postgresql://localhost:5433/javamicro
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: mysecretpassword
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true
    default-schema: diplom_netology_db
    contexts: prod
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: diplom_netology_db
    hibernate:
      ddl-auto: validate
  sql:
    init:
      mode: always
      continue-on-error: true
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    ru.netology: DEBUG
    org.springframework.web: INFO
  file:
    name: ./logs/cloudstore-prod-app.log
cors:
  settings:
    mapping: "/**"
    credentials: true
    origins: "http://localhost:8080"
    headers: "*"
    methods:
      - GET
      - POST
      - PUT
      - DELETE
project:
  filesystem:
    type: "docker"
---
spring:
  config:
    activate:
      on-profile: test
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:postgresql://localhost:5433/javamicro
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: mysecretpassword
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true
    default-schema: diplom_netology_db
    contexts: test
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: diplom_netology_db
    hibernate:
      ddl-auto: validate
  sql:
    init:
      mode: always
      continue-on-error: false
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    ru.netology: DEBUG
    org.springframework.web: INFO
  file:
    name: ./logs/cloudstore-test-app.log
cors:
  settings:
    mapping: "/**"
    credentials: true
    origins: "http://localhost:8080"
    headers: "*"
    methods:
      - GET
      - POST
      - PUT
      - DELETE
project:
  filesystem:
    type: "windows"

